export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_WALLET = "FETCH_USER_WALLET";

export const GET_SEND_TRANSACTION = "GET_SEND_TRANSACTION";
export const GET_RECEIVE_TRANSACTION = "GET_RECEIVE_TRANSACTION";
export const GET_INIT_TRANSACTION = "GET_INIT_TRANSACTION";
export const GET_PENDING_TRANSACTION = "GET_PENDING_TRANSACTION";
export const FETCH_SYSTEM_STATISTICS = "FETCH_SYSTEM_STATISTICS";
export const FETCH_ALL_USERS_INFORMATION = "FETCH_ALL_USERS_INFORMATION";
export const FETCH_ALL_TRANSACTION_INFORMATION =
  "FETCH_ALL_TRANSACTION_INFORMATION";
export const FETCH_ADDRESS_PAGE = "FETCH_ADDRESS_PAGE";
export const FETCH_TRANSACTION_PAGE = "FETCH_TRANSACTION_PAGE";
export const FETCH_USER_PAGE = "FETCH_USER_PAGE";

export const MESSAGE_EMAIL = "MESSAGE_EMAIL";
export const MESSAGE_INIT = "MESSAGE_INIT";
export const MESSAGE_CONFIRM = "MESSAGE_CONFIRM";
export const MESSAGE_CANCEL = "MESSAGE_CANCEL";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
