export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_WALLET = "FETCH_USER_WALLET";

export const GET_SEND_TRANSACTION = "GET_SEND_TRANSACTION";
export const GET_RECEIVE_TRANSACTION = "GET_RECEIVE_TRANSACTION";
export const GET_INIT_TRANSACTION = "GET_RECEIVE_TRANSACTION";
export const GET_PENDING_TRANSACTION = "GET_RECEIVE_TRANSACTION";
