export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_WALLET = "FETCH_USER_WALLET";
export const FETCH_SYSTEM_STATISTICS = "FETCH_SYSTEM_STATISTICS";
export const FETCH_ALL_USERS_INFORMATION = "FETCH_ALL_USERS_INFORMATION";
export const FETCH_ALL_TRANSACTION_INFORMATION =
  "FETCH_ALL_TRANSACTION_INFORMATION";
export const FETCH_ALL_ADDRESS_INFORMATION = "FETCH_ALL_ADDRESS_INFORMATION";
